plugin: gcp_compute
projects:
  - infra-262409
filters: []
# zones:
#   - europe-west-1b
auth_kind: serviceaccount
service_account_file: service_account.json
groups:
  app: "'reddit-app' in name"
  db: "'reddit-db' in name"
hostnames:
  - name
compose:
  ansible_host: networkInterfaces[0].accessConfigs[0].natIP
